@startuml herenca composicao

title Diagrama de Classes

class carteirinha_de_vacinação{
    - esquema básico: esquema básico
    - outras vacinas: outras vacinas
    - vacinas: vacinas
    - pessoa: pessoa
    - registro de carteirinha: registro de carteirinha
    - posto: posto
    + construtor(esquema básico, outras vacinas, vacinas, pessoa, registro de carteirinha, posto)
} 


esquema básico{
    - vacina1: vacina
    - vacina2: vacina
    - vacina3: vacina
    - vacina4: vacina 
} 
posto ( endereço - nome ) 

endereço( cep - rua - bairro - cidade - estado)

pessoa ( nome - cpf - rg - data nascimento - convênio - estado civil - end)

vacina ( nome - data - dose - fabricante - doença a tratar )



@enduml 