@startuml herenca composicao

title Diagrama de Classes

class carteirinha_de_vacinação{
    - esquema_básico: esquema_básico
    - outras_vacinas: outras_vacinas
    - vacinas: vacinas
    - pessoa: pessoa
    - registro_de_carteirinha: registro_de_carteirinha
    - posto: posto
    + construtor(esquema_básico, outras_vacinas, vacinas, pessoa, registro_de_carteirinha, posto)
} 


class esquema_básico{
    - bcg: String
    - hepatite: String
    - penta: String
    - rotavirus: String
    + construtor(bcg, hepatite, penta, rotavirus)
} 

class posto{
    - nome:String
    - endereco:endereco
    + construtor(nome, endereco)

}

class calendario_nacional_vacinacao{
    - bcg: String
    - hepatite: String
    - penta: String
    - rotavirus: String
    + construtor(bcg, hepatite, penta, rotavirus)
} 



class endereco{
    - cep:Int
    - rua:String
    - bairro: String
    - cidade: String
    + construtor(cep, rua, bairro, cidade)
}

class pessoa{
    - nome:String
    - cpf:String
    - rg: String
    - data_nascimento: String
    - estado_civil: String
    - endereco: endereco
    + construtor(nome, cpf, rg, data_nascimento, convenio, estado_civil, endereco)
}
class vacinas{
    - nome:String
    - data_fabricacao:String
    - dose: String
    - fabricante: String
    - doenca_tratar: String
    + construtor(nome, data_fabricacao, dose, fabricante, doenca_tratar)
}

class funcionario{
    - matricula:String
    - pessoa:pessoa
    - endereco: endereco
    - convenio: convenio
    + construtor(matricula, pessoa)

}

class paciente{
    - registro:String
    - historico: String
    - convenio: convenio
    - pessoa:pessoa
    - endereco: endereco
    + construtor(matricula, pessoa)
    }

class agendamento_ficha{
    - nficha:String
    - data: String
    - horario: convenio
    - paciente:paciente
    + construtor(nficha, data, horario, paciente)
    }


@enduml 